name: UpdatePlotpip install -r requirements.txt

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plot:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install required Python packages
        run: pip install -r requirements.txt

      - name: Update plot and CSV files
        run: python3 stackoverflow_plc.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update plots and CSVs with latest data
          
